### ISSUE TITLE
Win8 Install issues

### ISSUE THREAD

**Issue by johntom** [CharlesPockert/aurelia-grid#7]
Hi,
Your repo looks fantastic and I was quite excited to test but running into install issues. ( will try on mac later in week)
If you have any suggestions beside using a mac would love to hear them,
Thanks,
John
1) Win8 Pro, Node 0.12.6 npm  3.1.0
2) While I always get v8 errors durring npm install all other tests run fine including July version https://github.com/aurelia/skeleton-navigation
3) gulp watch blows up
```gulp watch
module.js:338
    throw err;
          ^
Error: Cannot find module 'jspm'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\a\build\tasks\bundle.js:2:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at requireDir (C:\a\node_modules\require-dir\index.js:112:33)
    at Object.<anonymous> (C:\a\gulpfile.js:3:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (C:\Users\Gateway PC\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (C:\Users\Gateway PC\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:192:
16)
    at module.exports (C:\Users\Gateway PC\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\node_modules\flagg
ed-respawn\index.js:17:3)
    at Liftoff.<anonymous> (C:\Users\Gateway PC\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:185:
9)
    at C:\Users\Gateway PC\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:159:9
    at C:\Users\Gateway PC\AppData\Roaming\npm\node_modules\gulp\node_modules\v8flags\index.js:79:12
    at C:\Users\Gateway PC\AppData\Roaming\npm\node_modules\gulp\node_modules\v8flags\index.js:35:7
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3```

**Comment by CharlesPockert** [comment]
Hi @johntom - there's a plugin version of the repo at http://github.com/charlespockert/aurelia-bs-grid - I've updated it today with a couple of fixes. It's not super-stable yet but should work ok. 

Can you try installing that one instead? 

This repo is going to be more of a counterpart "demo" of the grid.

Let me know if you manage to get it installed - for now I'll close this issue - if you want you can open an issue on the new repo if you are still having problems
